std: std.cpp core.hpp
	g++ std.cpp -o std -std=c++11

spfa: spfa.cpp core.hpp
	g++ spfa.cpp -o spfa -std=c++11

debug: debug.cpp core.hpp
	g++ debug.cpp -o debug -std=c++11

clean:
	rm std spfa debug
